services:
  - type: web
    name: blood-finder-backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: DB_URL
        value: jdbc:mysql://mysql-29eeef04-emergency-blood-finder-system.k.aivencloud.com:27037/defaultdb?useSSL=true
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
      - key: JWT_SECRET
        value: EmergencyBloodFinderSuperSecretKey2026!
